[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/blogs/*"
  to = "https://norouting-tensely--blank--kite-pgsdemo-com.preview.pagescdn.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://norouting-tensely--blank--kite-pgsdemo-com.preview.pagescdn.com/", Access-Control-Allow-Origin = "*" }

